{% set name = "rio-vrt" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e6dd8d483b748b0b800ebd1109c9d5be121185833aa4c061e7cbeda41c23ad40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6.9
    - setuptools >=61.2
    - wheel
    - pip
  run:
    - python >=3.6.9
    - rasterio

test:
  imports:
    - rio_vrt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/12rambau/rio-vrt
  summary: A simple librairy to build a vrt from multiple raster source relying only on rasterio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - savente93
