{% set name = "rio-vrt" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rio-vrt-{{ version }}.tar.gz
  sha256: da41e69e9acd230a811f0a07ba548957317bda69a23275e4a1b27bb033750893

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6.9
    - setuptools >=61.2
    - wheel
    - pip
  run:
    - python >=3.6.9
    - rasterio

test:
  imports:
    - rio_vrt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/12rambau/rio-vrt
  summary: A simple librairy to build a vrt from multiple raster source relying only on rasterio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - savente93
